alias ls='lsd'
alias l='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias lt='ls --tree'

alias cat='bat'

alias reload='source ~/.zshrc'

alias pna='pnpm add'
alias pnad='pnpm add --save-dev'
alias pnap='pnpm add --save-peer'
alias pnau='pnpm audit'
alias pnb='pnpm run build'
alias pnc='pnpm create'
alias pnd='pnpm run dev'
alias pndoc='pnpm run doc'
alias pnga='pnpm add --global'
alias pngls='pnpm list --global'
alias pngrm='pnpm remove --global'
alias pngu='pnpm update --global'
alias pnh='pnpm help'
alias pni='pnpm init'
alias pnin='pnpm install'
alias pnln='pnpm run lint'
alias pnls='pnpm list'
alias pnout='pnpm outdated'
alias pnp='pnpm'
alias pnpub='pnpm publish'
alias pnrm='pnpm remove'
alias pnrun='pnpm run'
alias pns='pnpm run serve'
alias pnst='pnpm start'
alias pnsv='pnpm server'
alias pnt='pnpm test'
alias pntc='pnpm test --coverage'
alias pnui='pnpm update --interactive'
alias pnuil='pnpm update --interactive --latest'
alias pnun='pnpm uninstall'
alias pnup='pnpm update'
alias pnwhy='pnpm why'
alias pnx='pnpx'

alias ba='bun add'
alias bad='bun add --save-dev'
alias bap='bun add --save-peer'
alias bu='bun'
alias bb='bun build'
alias bc='bun create'
alias bd='bun run dev'
alias bdoc='bun run doc'
alias bg='bun add --global'
alias bgl='bun list --global'
alias bgrm='bun remove --global'
alias bgu='bun update --global'
alias bh='bun help'
alias bi='bun init'
alias bin='bun install'
alias bln='bun run lint'
alias bls='bun list'
alias bout='bun outdated'
alias bpub='bun publish'
alias brm='bun remove'
alias brun='bun run'
alias bs='bun run serve'
alias bst='bun start'
alias bsv='bun server'
alias bt='bun test'
alias bui='bun update --interactive'
alias buil='bun update --interactive --latest'
alias bwhy='bun why'

function mkcd {
  if [ ! -n "$1" ]; then
    echo "Enter a directory name"
  elif [ -d $1 ]; then
    echo "\`$1' already exists"
  else
    mkdir $1 && cd $1
  fi
}